In [1]:
import numpy as np 
import pandas as pd

**Pivot Tables**

In [2]:
data = {
    'Date': pd.date_range('2026-2-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

In [3]:
df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep     Month Quarter
0  2026-02-01       A   East    478     90   John  February      Q1
1  2026-02-02       B   West    685     46   Mary  February      Q1
2  2026-02-03       C  North    987     36    Bob  February      Q1
3  2026-02-04       D  South    903     45  Alice  February      Q1
4  2026-02-05       A   East    952     91   John  February      Q1
5  2026-02-06       B   West    357     58   Mary  February      Q1
6  2026-02-07       C  North    813     92    Bob  February      Q1
7  2026-02-08       D  South    403     58  Alice  February      Q1
8  2026-02-09       A   East    810     64   John  February      Q1
9  2026-02-10       B   West    670     84   Mary  February      Q1
10 2026-02-11       C  North    145     63    Bob  February      Q1
11 2026-02-12       D  South    957     52  Alice  February      Q1
12 2026-02-13       A   East    772     94   John  February      Q1
13 2026-02-14       B   West    163     20   Mary  February      Q1
14 2026-02-15       C  North    751     74    Bob  February      Q1
15 2026-02-16       D  South    287     15  Alice  February      Q1
16 2026-02-17       A   East    471     66   John  February      Q1
17 2026-02-18       B   West    265     58   Mary  February      Q1
18 2026-02-19       C  North    228     31    Bob  February      Q1
19 2026-02-20       D  South    185     92  Alice  February      Q1

In [4]:
pd.pivot_table(df,values = "Sales",index = 'Region',columns="Product",aggfunc = 'median')

Product      A      B      C      D
Region
East     772.0    NaN    NaN    NaN
North      NaN    NaN  751.0    NaN
South      NaN    NaN    NaN  403.0
West       NaN  357.0    NaN    NaN

In [5]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     696.6    NaN    NaN    NaN  81.0   NaN   NaN   NaN
North      NaN    NaN  584.8    NaN   NaN   NaN  59.2   NaN
South      NaN    NaN    NaN  547.0   NaN   NaN   NaN  52.4
West       NaN  428.0    NaN    NaN   NaN  53.2   NaN   NaN

**Cross Tabs**

In [6]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0